/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0e141a",
        "surface-dim": "#0e141a",
        "surface-bright": "#343a41",
        "surface-container-lowest": "#090f15",
        "surface-container-low": "#161c23",
        "surface-container": "#1a2027",
        "surface-container-high": "#252a31",
        "surface-container-highest": "#2f353c",
        "on-surface": "#dde3ec",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#dde3ec",
        "inverse-on-surface": "#2b3138",
        "outline": "#849495",
        "outline-variant": "#3a494b",
        "surface-tint": "#00dbe7",
        "primary": "#e1fdff",
        "on-primary": "#00363a",
        "primary-container": "#00f2ff",
        "on-primary-container": "#006a71",
        "inverse-primary": "#00696f",
        "primary-fixed": "#74f5ff",
        "primary-fixed-dim": "#00dbe7",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "secondary": "#ebb2ff",
        "on-secondary": "#520071",
        "secondary-container": "#ce5dff",
        "on-secondary-container": "#480064",
        "secondary-fixed": "#f8d8ff",
        "secondary-fixed-dim": "#ebb2ff",
        "on-secondary-fixed": "#320047",
        "on-secondary-fixed-variant": "#74009f",
        "tertiary": "#fff5f8",
        "on-tertiary": "#5e0053",
        "tertiary-container": "#ffccee",
        "on-tertiary-container": "#af009d",
        "tertiary-fixed": "#ffd7f0",
        "tertiary-fixed-dim": "#fface8",
        "on-tertiary-fixed": "#3a0033",
        "on-tertiary-fixed-variant": "#840076",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "warning-orange": "#ffaa00",
        "glow-cyan": "rgba(0, 242, 255, 0.4)",
        "glass-surface": "rgba(5, 10, 16, 0.7)",
        "background": "#0e141a",
        "on-background": "#dde3ec",
        "surface-variant": "#2f353c",
        "absolute-black": "#000000",
        "safe-green": "#4edea3",
        "alert-red": "#ff4d4d",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "glass-padding": "24px",
        "unit": "4px",
        "gutter": "20px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Sora", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      dropShadow: {
        "glow-cyan": "0 0 10px rgba(0, 242, 255, 0.6)",
        "glow-cyan-lg": "0 0 20px rgba(0, 242, 255, 0.4)",
      },
      boxShadow: {
        "glow-cyan": "0 0 20px rgba(0, 242, 255, 0.4)",
        "glow-cyan-intense": "0 0 40px rgba(0, 242, 255, 0.6)",
      }
    },
  },
  plugins: [],
}
